site_name: Yoto Up Documentation
theme:
  name: material
  features:
    - navigation.tabs
docs_dir: docs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite

site_url: "https://xkjq.github.io/yoto-up/"
repo_url: "https://github.com/xkjq/yoto-up"