site_name: Yoto Up Documentation
theme:
  name: material
  features:
    - navigation.tabs
docs_dir: docs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
